name: fynaura
description: "A new Flutter project."

publish_to: 'none'  # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ">=3.5.4 <4.0.0"  # Make sure your SDK is compatible

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  flutter_screenutil: ^5.9.3
  http: ^0.13.3
  shared_preferences: ^2.5.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_launcher_icons: "^0.14.2"

flutter_launcher_icons:
  android: true  # Set to true for generating launcher icon on Android
  ios: true      # Set to true for iOS platform
  image_path: "images/fynaura.png"  # Path to the image used for the app icon

flutter_lints: ^4.0.0

flutter:
  uses-material-design: true

  assets:
    - images/fynaura.png
    - images/fynaura-icon.png
    - images/google.png
    - images/fb.png
    - images/apple.png
    - images/cellphone.png
