name: fynaura
description: "A new Flutter project."

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=3.5.4 <4.0.0"

dependencies:
  flutter_plugin_android_lifecycle: ^2.0.15
  image_picker: ^1.0.4
  #  image_picker_android: ^0.8.12+21
  flutter:
    sdk: flutter

  http: 1.3.0
  intl: ^0.18.0
  http_parser: ^4.0.2
  uuid: ^3.0.7
  mime: ^2.0.0
  mobile_scanner: ^3.0.0
  qr_flutter: ^4.1.0
  flutter_secure_storage: ^8.0.0
  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.8
  flutter_screenutil: ^5.9.3
  confetti: ^0.6.0
  fl_chart: ^0.68.0
  shared_preferences: ^2.4.0 
  timezone: ^0.10.0
  flutter_local_notifications: ^18.0.1
  permission_handler: ^11.4.0



dev_dependencies:
  mockito: ^5.4.4
  provider: ^6.1.0
  flutter_test:
    sdk: flutter
  flutter_launcher_icons: "^0.14.2"
flutter_launcher_icons:
  android: true
  ios: true
  image_path: "images/fynaura.png"  # Main image for app icon

flutter_lints: ^4.0.0

flutter:
  uses-material-design: true

  assets:

    - images/fynaura.png
    - images/fynaura-icon.png
    - images/google.png
    - images/fb.png
    - images/apple.png
    - images/cellphone.png
    - images/splash.gif
    - images/user.png




  #   - images/a_dot_ham.jpeg

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/to/resolution-aware-images

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/to/asset-from-package

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/to/font-from-package

