name: fynaura
description: "A new Flutter project."
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The version number for your app
version: 1.0.0+1

environment:
  sdk: ">=3.7.0 <4.0.0"  # Updated to be compatible with the latest Flutter SDK

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  flutter_screenutil: ^5.9.3
  http: ^0.13.3  # Downgraded version of `http` to avoid conflicts

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_launcher_icons: "^0.14.2"  # Make sure this is compatible with your Flutter version
  flutter_lints: ^4.0.0  # Ensure this is the latest version

flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "images/fynaura.png"

flutter:
  uses-material-design: true

  # Add assets section with images and icons
  assets:
    - images/fynaura.png
    - images/fynaura-icon.png
    - images/google.png
    - images/fb.png
    - images/apple.png
    - images/cellphone.png
