import spacy
from spacy.training.example import Example
import random
from sklearn.model_selection import train_test_split
import pandas as pd

# Load or create a blank model
try:
    nlp = spacy.load("expense_nlp")
    print("Loaded existing model.")
except OSError:
    nlp = spacy.blank("en")
    print("Creating new model.")

# Create or get the textcat component
if "textcat" not in nlp.pipe_names:
    textcat = nlp.add_pipe("textcat", last=True)
else:
    textcat = nlp.get_pipe("textcat")

# Define expense categories
categories = ["Food", "Electronics", "Transport", "Bills", "Clothes", "Phone",
              "Sport", "Education", "Medical", "Beauty", "Grocery", "Vehicle"]

for category in categories:
    textcat.add_label(category)

# Enhanced training data - add more single-item examples
# Enhanced training data with 100 examples per category
TRAINING_DATA = [
    # GROCERY CATEGORY (100 examples)
    ("carrots", {"cats": {"Grocery": 1.0}}),
    ("tomatoes", {"cats": {"Grocery": 1.0}}),
    ("apples", {"cats": {"Grocery": 1.0}}),
    ("milk", {"cats": {"Grocery": 1.0}}),
    ("bread", {"cats": {"Grocery": 1.0}}),
    ("rice", {"cats": {"Grocery": 1.0}}),
    ("bananas", {"cats": {"Grocery": 1.0}}),
    ("potatoes", {"cats": {"Grocery": 1.0}}),
    ("cereal", {"cats": {"Grocery": 1.0}}),
    ("eggs", {"cats": {"Grocery": 1.0}}),
    ("butter", {"cats": {"Grocery": 1.0}}),
    ("cheese", {"cats": {"Grocery": 1.0}}),
    ("yogurt", {"cats": {"Grocery": 1.0}}),
    ("flour", {"cats": {"Grocery": 1.0}}),
    ("sugar", {"cats": {"Grocery": 1.0}}),
    ("salt", {"cats": {"Grocery": 1.0}}),
    ("pepper", {"cats": {"Grocery": 1.0}}),
    ("pasta", {"cats": {"Grocery": 1.0}}),
    ("rice", {"cats": {"Grocery": 1.0}}),
    ("beans", {"cats": {"Grocery": 1.0}}),
    ("lentils", {"cats": {"Grocery": 1.0}}),
    ("chickpeas", {"cats": {"Grocery": 1.0}}),
    ("canned tomatoes", {"cats": {"Grocery": 1.0}}),
    ("tuna", {"cats": {"Grocery": 1.0}}),
    ("salmon", {"cats": {"Grocery": 1.0}}),
    ("chicken", {"cats": {"Grocery": 1.0}}),
    ("beef", {"cats": {"Grocery": 1.0}}),
    ("pork", {"cats": {"Grocery": 1.0}}),
    ("sausages", {"cats": {"Grocery": 1.0}}),
    ("bacon", {"cats": {"Grocery": 1.0}}),
    ("ham", {"cats": {"Grocery": 1.0}}),
    ("onions", {"cats": {"Grocery": 1.0}}),
    ("garlic", {"cats": {"Grocery": 1.0}}),
    ("ginger", {"cats": {"Grocery": 1.0}}),
    ("broccoli", {"cats": {"Grocery": 1.0}}),
    ("cauliflower", {"cats": {"Grocery": 1.0}}),
    ("lettuce", {"cats": {"Grocery": 1.0}}),
    ("spinach", {"cats": {"Grocery": 1.0}}),
    ("kale", {"cats": {"Grocery": 1.0}}),
    ("oranges", {"cats": {"Grocery": 1.0}}),
    ("lemons", {"cats": {"Grocery": 1.0}}),
    ("limes", {"cats": {"Grocery": 1.0}}),
    ("grapes", {"cats": {"Grocery": 1.0}}),
    ("strawberries", {"cats": {"Grocery": 1.0}}),
    ("blueberries", {"cats": {"Grocery": 1.0}}),
    ("raspberries", {"cats": {"Grocery": 1.0}}),
    ("blackberries", {"cats": {"Grocery": 1.0}}),
    ("watermelon", {"cats": {"Grocery": 1.0}}),
    ("pineapple", {"cats": {"Grocery": 1.0}}),
    ("mango", {"cats": {"Grocery": 1.0}}),
    ("avocado", {"cats": {"Grocery": 1.0}}),
    ("corn", {"cats": {"Grocery": 1.0}}),
    ("peas", {"cats": {"Grocery": 1.0}}),
    ("green beans", {"cats": {"Grocery": 1.0}}),
    ("mushrooms", {"cats": {"Grocery": 1.0}}),
    ("tofu", {"cats": {"Grocery": 1.0}}),
    ("olive oil", {"cats": {"Grocery": 1.0}}),
    ("vegetable oil", {"cats": {"Grocery": 1.0}}),
    ("coconut oil", {"cats": {"Grocery": 1.0}}),
    ("honey", {"cats": {"Grocery": 1.0}}),
    ("maple syrup", {"cats": {"Grocery": 1.0}}),
    ("jam", {"cats": {"Grocery": 1.0}}),
    ("peanut butter", {"cats": {"Grocery": 1.0}}),
    ("nutella", {"cats": {"Grocery": 1.0}}),
    ("ketchup", {"cats": {"Grocery": 1.0}}),
    ("mustard", {"cats": {"Grocery": 1.0}}),
    ("mayonnaise", {"cats": {"Grocery": 1.0}}),
    ("soy sauce", {"cats": {"Grocery": 1.0}}),
    ("vinegar", {"cats": {"Grocery": 1.0}}),
    ("pasta sauce", {"cats": {"Grocery": 1.0}}),
    ("curry sauce", {"cats": {"Grocery": 1.0}}),
    ("salsa", {"cats": {"Grocery": 1.0}}),
    ("guacamole", {"cats": {"Grocery": 1.0}}),
    ("hummus", {"cats": {"Grocery": 1.0}}),
    ("toilet paper", {"cats": {"Grocery": 1.0}}),
    ("paper towels", {"cats": {"Grocery": 1.0}}),
    ("dish soap", {"cats": {"Grocery": 1.0}}),
    ("laundry detergent", {"cats": {"Grocery": 1.0}}),
    ("soap", {"cats": {"Grocery": 1.0}}),
    ("tissues", {"cats": {"Grocery": 1.0}}),
    ("aluminum foil", {"cats": {"Grocery": 1.0}}),
    ("plastic wrap", {"cats": {"Grocery": 1.0}}),
    ("freezer bags", {"cats": {"Grocery": 1.0}}),
    ("sandwich bags", {"cats": {"Grocery": 1.0}}),
    ("trash bags", {"cats": {"Grocery": 1.0}}),
    ("napkins", {"cats": {"Grocery": 1.0}}),
    ("cleaning supplies", {"cats": {"Grocery": 1.0}}),
    ("disinfectant wipes", {"cats": {"Grocery": 1.0}}),
    ("sponges", {"cats": {"Grocery": 1.0}}),
    ("household cleaners", {"cats": {"Grocery": 1.0}}),
    ("pet food", {"cats": {"Grocery": 1.0}}),
    ("cat litter", {"cats": {"Grocery": 1.0}}),
    ("dog treats", {"cats": {"Grocery": 1.0}}),
    ("pet supplies", {"cats": {"Grocery": 1.0}}),
    ("fresh produce", {"cats": {"Grocery": 1.0}}),
    ("deli items", {"cats": {"Grocery": 1.0}}),
    ("bakery goods", {"cats": {"Grocery": 1.0}}),
    ("pantry staples", {"cats": {"Grocery": 1.0}}),

    # FOOD CATEGORY (100 examples) - Restaurant/Takeout food
    ("pizza", {"cats": {"Food": 1.0}}),
    ("burger", {"cats": {"Food": 1.0}}),
    ("french fries", {"cats": {"Food": 1.0}}),
    ("chicken nuggets", {"cats": {"Food": 1.0}}),
    ("hot dog", {"cats": {"Food": 1.0}}),
    ("sandwich", {"cats": {"Food": 1.0}}),
    ("sushi", {"cats": {"Food": 1.0}}),
    ("ramen", {"cats": {"Food": 1.0}}),
    ("pasta dish", {"cats": {"Food": 1.0}}),
    ("salad bar", {"cats": {"Food": 1.0}}),
    ("tacos", {"cats": {"Food": 1.0}}),
    ("burritos", {"cats": {"Food": 1.0}}),
    ("nachos", {"cats": {"Food": 1.0}}),
    ("quesadilla", {"cats": {"Food": 1.0}}),
    ("enchiladas", {"cats": {"Food": 1.0}}),
    ("fried rice", {"cats": {"Food": 1.0}}),
    ("chow mein", {"cats": {"Food": 1.0}}),
    ("pad thai", {"cats": {"Food": 1.0}}),
    ("curry dish", {"cats": {"Food": 1.0}}),
    ("biryani", {"cats": {"Food": 1.0}}),
    ("tikka masala", {"cats": {"Food": 1.0}}),
    ("naan bread", {"cats": {"Food": 1.0}}),
    ("samosas", {"cats": {"Food": 1.0}}),
    ("spring rolls", {"cats": {"Food": 1.0}}),
    ("dumplings", {"cats": {"Food": 1.0}}),
    ("pho", {"cats": {"Food": 1.0}}),
    ("bibimbap", {"cats": {"Food": 1.0}}),
    ("shawarma", {"cats": {"Food": 1.0}}),
    ("falafel", {"cats": {"Food": 1.0}}),
    ("kebab", {"cats": {"Food": 1.0}}),
    ("gyro", {"cats": {"Food": 1.0}}),
    ("fish and chips", {"cats": {"Food": 1.0}}),
    ("steak", {"cats": {"Food": 1.0}}),
    ("ribs", {"cats": {"Food": 1.0}}),
    ("barbecue", {"cats": {"Food": 1.0}}),
    ("fried chicken", {"cats": {"Food": 1.0}}),
    ("chicken wings", {"cats": {"Food": 1.0}}),
    ("meatballs", {"cats": {"Food": 1.0}}),
    ("lasagna", {"cats": {"Food": 1.0}}),
    ("mac and cheese", {"cats": {"Food": 1.0}}),
    ("soup", {"cats": {"Food": 1.0}}),
    ("chili", {"cats": {"Food": 1.0}}),
    ("clam chowder", {"cats": {"Food": 1.0}}),
    ("lobster", {"cats": {"Food": 1.0}}),
    ("crab", {"cats": {"Food": 1.0}}),
    ("shrimp", {"cats": {"Food": 1.0}}),
    ("oysters", {"cats": {"Food": 1.0}}),
    ("scallops", {"cats": {"Food": 1.0}}),
    ("mussels", {"cats": {"Food": 1.0}}),
    ("calamari", {"cats": {"Food": 1.0}}),
    ("paella", {"cats": {"Food": 1.0}}),
    ("risotto", {"cats": {"Food": 1.0}}),
    ("gnocchi", {"cats": {"Food": 1.0}}),
    ("carbonara", {"cats": {"Food": 1.0}}),
    ("alfredo", {"cats": {"Food": 1.0}}),
    ("pesto pasta", {"cats": {"Food": 1.0}}),
    ("pizza delivery", {"cats": {"Food": 1.0}}),
    ("takeout order", {"cats": {"Food": 1.0}}),
    ("restaurant meal", {"cats": {"Food": 1.0}}),
    ("drive-thru", {"cats": {"Food": 1.0}}),
    ("dine-in", {"cats": {"Food": 1.0}}),
    ("buffet", {"cats": {"Food": 1.0}}),
    ("food truck", {"cats": {"Food": 1.0}}),
    ("cafe", {"cats": {"Food": 1.0}}),
    ("coffee shop", {"cats": {"Food": 1.0}}),
    ("espresso", {"cats": {"Food": 1.0}}),
    ("cappuccino", {"cats": {"Food": 1.0}}),
    ("latte", {"cats": {"Food": 1.0}}),
    ("mocha", {"cats": {"Food": 1.0}}),
    ("smoothie", {"cats": {"Food": 1.0}}),
    ("milkshake", {"cats": {"Food": 1.0}}),
    ("juice bar", {"cats": {"Food": 1.0}}),
    ("ice cream", {"cats": {"Food": 1.0}}),
    ("frozen yogurt", {"cats": {"Food": 1.0}}),
    ("gelato", {"cats": {"Food": 1.0}}),
    ("sorbet", {"cats": {"Food": 1.0}}),
    ("cake", {"cats": {"Food": 1.0}}),
    ("pie", {"cats": {"Food": 1.0}}),
    ("cookies", {"cats": {"Food": 1.0}}),
    ("pastry", {"cats": {"Food": 1.0}}),
    ("croissant", {"cats": {"Food": 1.0}}),
    ("donut", {"cats": {"Food": 1.0}}),
    ("muffin", {"cats": {"Food": 1.0}}),
    ("bagel", {"cats": {"Food": 1.0}}),
    ("breakfast sandwich", {"cats": {"Food": 1.0}}),
    ("brunch", {"cats": {"Food": 1.0}}),
    ("lunch special", {"cats": {"Food": 1.0}}),
    ("dinner", {"cats": {"Food": 1.0}}),
    ("fast food", {"cats": {"Food": 1.0}}),
    ("fine dining", {"cats": {"Food": 1.0}}),
    ("food delivery fee", {"cats": {"Food": 1.0}}),
    ("tip for waiter", {"cats": {"Food": 1.0}}),
    ("restaurant tip", {"cats": {"Food": 1.0}}),
    ("meal combo", {"cats": {"Food": 1.0}}),
    ("value meal", {"cats": {"Food": 1.0}}),
    ("kids meal", {"cats": {"Food": 1.0}}),
    ("family dinner", {"cats": {"Food": 1.0}}),

    # ELECTRONICS CATEGORY (100 examples)
    ("laptop", {"cats": {"Electronics": 1.0}}),
    ("smartphone", {"cats": {"Electronics": 1.0}}),
    ("tablet", {"cats": {"Electronics": 1.0}}),
    ("desktop computer", {"cats": {"Electronics": 1.0}}),
    ("monitor", {"cats": {"Electronics": 1.0}}),
    ("keyboard", {"cats": {"Electronics": 1.0}}),
    ("mouse", {"cats": {"Electronics": 1.0}}),
    ("headphones", {"cats": {"Electronics": 1.0}}),
    ("speakers", {"cats": {"Electronics": 1.0}}),
    ("television", {"cats": {"Electronics": 1.0}}),
    ("TV", {"cats": {"Electronics": 1.0}}),
    ("smart TV", {"cats": {"Electronics": 1.0}}),
    ("DVD player", {"cats": {"Electronics": 1.0}}),
    ("Blu-ray player", {"cats": {"Electronics": 1.0}}),
    ("streaming device", {"cats": {"Electronics": 1.0}}),
    ("Roku", {"cats": {"Electronics": 1.0}}),
    ("Apple TV", {"cats": {"Electronics": 1.0}}),
    ("Chromecast", {"cats": {"Electronics": 1.0}}),
    ("Amazon Fire Stick", {"cats": {"Electronics": 1.0}}),
    ("gaming console", {"cats": {"Electronics": 1.0}}),
    ("PlayStation", {"cats": {"Electronics": 1.0}}),
    ("Xbox", {"cats": {"Electronics": 1.0}}),
    ("Nintendo Switch", {"cats": {"Electronics": 1.0}}),
    ("video game", {"cats": {"Electronics": 1.0}}),
    ("game controller", {"cats": {"Electronics": 1.0}}),
    ("webcam", {"cats": {"Electronics": 1.0}}),
    ("microphone", {"cats": {"Electronics": 1.0}}),
    ("printer", {"cats": {"Electronics": 1.0}}),
    ("scanner", {"cats": {"Electronics": 1.0}}),
    ("ink cartridge", {"cats": {"Electronics": 1.0}}),
    ("toner", {"cats": {"Electronics": 1.0}}),
    ("router", {"cats": {"Electronics": 1.0}}),
    ("modem", {"cats": {"Electronics": 1.0}}),
    ("wireless access point", {"cats": {"Electronics": 1.0}}),
    ("ethernet cable", {"cats": {"Electronics": 1.0}}),
    ("HDMI cable", {"cats": {"Electronics": 1.0}}),
    ("USB cable", {"cats": {"Electronics": 1.0}}),
    ("power cable", {"cats": {"Electronics": 1.0}}),
    ("charging cable", {"cats": {"Electronics": 1.0}}),
    ("phone charger", {"cats": {"Electronics": 1.0}}),
    ("laptop charger", {"cats": {"Electronics": 1.0}}),
    ("power adapter", {"cats": {"Electronics": 1.0}}),
    ("power bank", {"cats": {"Electronics": 1.0}}),
    ("battery", {"cats": {"Electronics": 1.0}}),
    ("rechargeable battery", {"cats": {"Electronics": 1.0}}),
    ("AAA batteries", {"cats": {"Electronics": 1.0}}),
    ("AA batteries", {"cats": {"Electronics": 1.0}}),
    ("camera", {"cats": {"Electronics": 1.0}}),
    ("digital camera", {"cats": {"Electronics": 1.0}}),
    ("DSLR camera", {"cats": {"Electronics": 1.0}}),
    ("camera lens", {"cats": {"Electronics": 1.0}}),
    ("tripod", {"cats": {"Electronics": 1.0}}),
    ("memory card", {"cats": {"Electronics": 1.0}}),
    ("SD card", {"cats": {"Electronics": 1.0}}),
    ("USB drive", {"cats": {"Electronics": 1.0}}),
    ("external hard drive", {"cats": {"Electronics": 1.0}}),
    ("SSD", {"cats": {"Electronics": 1.0}}),
    ("NAS", {"cats": {"Electronics": 1.0}}),
    ("smart watch", {"cats": {"Electronics": 1.0}}),
    ("Apple Watch", {"cats": {"Electronics": 1.0}}),
    ("Fitbit", {"cats": {"Electronics": 1.0}}),
    ("Garmin watch", {"cats": {"Electronics": 1.0}}),
    ("wireless earbuds", {"cats": {"Electronics": 1.0}}),
    ("AirPods", {"cats": {"Electronics": 1.0}}),
    ("Bluetooth headset", {"cats": {"Electronics": 1.0}}),
    ("graphic card", {"cats": {"Electronics": 1.0}}),
    ("CPU", {"cats": {"Electronics": 1.0}}),
    ("RAM", {"cats": {"Electronics": 1.0}}),
    ("motherboard", {"cats": {"Electronics": 1.0}}),
    ("computer case", {"cats": {"Electronics": 1.0}}),
    ("power supply", {"cats": {"Electronics": 1.0}}),
    ("cooling fan", {"cats": {"Electronics": 1.0}}),
    ("thermal paste", {"cats": {"Electronics": 1.0}}),
    ("electronic repair", {"cats": {"Electronics": 1.0}}),
    ("screen protector", {"cats": {"Electronics": 1.0}}),
    ("phone case", {"cats": {"Electronics": 1.0}}),
    ("laptop bag", {"cats": {"Electronics": 1.0}}),
    ("cable organizer", {"cats": {"Electronics": 1.0}}),
    ("surge protector", {"cats": {"Electronics": 1.0}}),
    ("power strip", {"cats": {"Electronics": 1.0}}),
    ("universal remote", {"cats": {"Electronics": 1.0}}),
    ("smart speaker", {"cats": {"Electronics": 1.0}}),
    ("Amazon Echo", {"cats": {"Electronics": 1.0}}),
    ("Google Home", {"cats": {"Electronics": 1.0}}),
    ("smart bulb", {"cats": {"Electronics": 1.0}}),
    ("smart plug", {"cats": {"Electronics": 1.0}}),
    ("security camera", {"cats": {"Electronics": 1.0}}),
    ("doorbell camera", {"cats": {"Electronics": 1.0}}),
    ("drone", {"cats": {"Electronics": 1.0}}),
    ("VR headset", {"cats": {"Electronics": 1.0}}),
    ("projector", {"cats": {"Electronics": 1.0}}),
    ("calculator", {"cats": {"Electronics": 1.0}}),
    ("electronic dictionary", {"cats": {"Electronics": 1.0}}),
    ("e-reader", {"cats": {"Electronics": 1.0}}),
    ("Kindle", {"cats": {"Electronics": 1.0}}),
    ("light bulb", {"cats": {"Electronics": 1.0}}),
    ("LED light", {"cats": {"Electronics": 1.0}}),

    # TRANSPORT CATEGORY (100 examples)
    ("bus ticket", {"cats": {"Transport": 1.0}}),
    ("train ticket", {"cats": {"Transport": 1.0}}),
    ("subway fare", {"cats": {"Transport": 1.0}}),
    ("metro card", {"cats": {"Transport": 1.0}}),
    ("bus pass", {"cats": {"Transport": 1.0}}),
    ("monthly transit pass", {"cats": {"Transport": 1.0}}),
    ("tram ticket", {"cats": {"Transport": 1.0}}),
    ("ferry ticket", {"cats": {"Transport": 1.0}}),
    ("taxi fare", {"cats": {"Transport": 1.0}}),
    ("Uber ride", {"cats": {"Transport": 1.0}}),
    ("Lyft ride", {"cats": {"Transport": 1.0}}),
    ("rideshare", {"cats": {"Transport": 1.0}}),
    ("airport shuttle", {"cats": {"Transport": 1.0}}),
    ("airport transfer", {"cats": {"Transport": 1.0}}),
    ("limousine service", {"cats": {"Transport": 1.0}}),
    ("car rental", {"cats": {"Transport": 1.0}}),
    ("rental car", {"cats": {"Transport": 1.0}}),
    ("scooter rental", {"cats": {"Transport": 1.0}}),
    ("bike rental", {"cats": {"Transport": 1.0}}),
    ("bike sharing", {"cats": {"Transport": 1.0}}),
    ("car sharing", {"cats": {"Transport": 1.0}}),
    ("airline ticket", {"cats": {"Transport": 1.0}}),
    ("flight", {"cats": {"Transport": 1.0}}),
    ("plane ticket", {"cats": {"Transport": 1.0}}),
    ("domestic flight", {"cats": {"Transport": 1.0}}),
    ("international flight", {"cats": {"Transport": 1.0}}),
    ("business class ticket", {"cats": {"Transport": 1.0}}),
    ("economy class ticket", {"cats": {"Transport": 1.0}}),
    ("first class ticket", {"cats": {"Transport": 1.0}}),
    ("checked baggage fee", {"cats": {"Transport": 1.0}}),
    ("excess baggage fee", {"cats": {"Transport": 1.0}}),
    ("airport parking", {"cats": {"Transport": 1.0}}),
    ("long-term parking", {"cats": {"Transport": 1.0}}),
    ("short-term parking", {"cats": {"Transport": 1.0}}),
    ("valet parking", {"cats": {"Transport": 1.0}}),
    ("parking meter", {"cats": {"Transport": 1.0}}),
    ("parking garage", {"cats": {"Transport": 1.0}}),
    ("parking lot", {"cats": {"Transport": 1.0}}),
    ("street parking", {"cats": {"Transport": 1.0}}),
    ("resident parking permit", {"cats": {"Transport": 1.0}}),
    ("toll road", {"cats": {"Transport": 1.0}}),
    ("highway toll", {"cats": {"Transport": 1.0}}),
    ("bridge toll", {"cats": {"Transport": 1.0}}),
    ("tunnel toll", {"cats": {"Transport": 1.0}}),
    ("congestion charge", {"cats": {"Transport": 1.0}}),
    ("electronic toll collection", {"cats": {"Transport": 1.0}}),
    ("E-ZPass", {"cats": {"Transport": 1.0}}),
    ("FastTrak", {"cats": {"Transport": 1.0}}),
    ("SunPass", {"cats": {"Transport": 1.0}}),
    ("TollTag", {"cats": {"Transport": 1.0}}),
    ("cruise ticket", {"cats": {"Transport": 1.0}}),
    ("cruise fare", {"cats": {"Transport": 1.0}}),
    ("cruise shore excursion", {"cats": {"Transport": 1.0}}),
    ("helicopter tour", {"cats": {"Transport": 1.0}}),
    ("hot air balloon ride", {"cats": {"Transport": 1.0}}),
    ("tour bus", {"cats": {"Transport": 1.0}}),
    ("city tour", {"cats": {"Transport": 1.0}}),
    ("sightseeing tour", {"cats": {"Transport": 1.0}}),
    ("day trip", {"cats": {"Transport": 1.0}}),
    ("travel insurance", {"cats": {"Transport": 1.0}}),
    ("luggage", {"cats": {"Transport": 1.0}}),
    ("suitcase", {"cats": {"Transport": 1.0}}),
    ("travel adapter", {"cats": {"Transport": 1.0}}),
    ("travel pillow", {"cats": {"Transport": 1.0}}),
    ("travel wallet", {"cats": {"Transport": 1.0}}),
    ("passport photo", {"cats": {"Transport": 1.0}}),
    ("passport renewal", {"cats": {"Transport": 1.0}}),
    ("visa application", {"cats": {"Transport": 1.0}}),
    ("visa fee", {"cats": {"Transport": 1.0}}),
    ("tourist visa", {"cats": {"Transport": 1.0}}),
    ("business visa", {"cats": {"Transport": 1.0}}),
    ("transit visa", {"cats": {"Transport": 1.0}}),
    ("currency exchange", {"cats": {"Transport": 1.0}}),
    ("foreign currency", {"cats": {"Transport": 1.0}}),
    ("travel agency", {"cats": {"Transport": 1.0}}),
    ("tour package", {"cats": {"Transport": 1.0}}),
    ("vacation package", {"cats": {"Transport": 1.0}}),
    ("all-inclusive package", {"cats": {"Transport": 1.0}}),
    ("travel guide", {"cats": {"Transport": 1.0}}),
    ("city map", {"cats": {"Transport": 1.0}}),
    ("travel guidebook", {"cats": {"Transport": 1.0}}),
    ("travel sim card", {"cats": {"Transport": 1.0}}),
    ("international roaming", {"cats": {"Transport": 1.0}}),
    ("travel wifi", {"cats": {"Transport": 1.0}}),
    ("portable wifi device", {"cats": {"Transport": 1.0}}),
    ("airport lounge access", {"cats": {"Transport": 1.0}}),
    ("priority boarding", {"cats": {"Transport": 1.0}}),
    ("seat upgrade", {"cats": {"Transport": 1.0}}),
    ("travel vaccination", {"cats": {"Transport": 1.0}}),
    ("travel medicine", {"cats": {"Transport": 1.0}}),
    ("road trip", {"cats": {"Transport": 1.0}}),
    ("commuter pass", {"cats": {"Transport": 1.0}}),
    ("student travel card", {"cats": {"Transport": 1.0}}),
    ("senior transit discount", {"cats": {"Transport": 1.0}}),
    ("child fare", {"cats": {"Transport": 1.0}}),
    ("group ticket", {"cats": {"Transport": 1.0}}),
    ("one-way ticket", {"cats": {"Transport": 1.0}}),
    ("round-trip ticket", {"cats": {"Transport": 1.0}}),
    ("express train", {"cats": {"Transport": 1.0}}),

    # BILLS CATEGORY (100 examples)
    ("electricity bill", {"cats": {"Bills": 1.0}}),
    ("water bill", {"cats": {"Bills": 1.0}}),
    ("gas bill", {"cats": {"Bills": 1.0}}),
    ("internet bill", {"cats": {"Bills": 1.0}}),
    ("cable TV bill", {"cats": {"Bills": 1.0}}),
    ("phone bill", {"cats": {"Bills": 1.0}}),
    ("mobile phone bill", {"cats": {"Bills": 1.0}}),
    ("landline bill", {"cats": {"Bills": 1.0}}),
    ("rent payment", {"cats": {"Bills": 1.0}}),
    ("mortgage payment", {"cats": {"Bills": 1.0}}),
    ("property tax", {"cats": {"Bills": 1.0}}),
    ("homeowners association fee", {"cats": {"Bills": 1.0}}),
    ("HOA fee", {"cats": {"Bills": 1.0}}),
    ("condo fee", {"cats": {"Bills": 1.0}}),
    ("maintenance fee", {"cats": {"Bills": 1.0}}),
    ("sewer bill", {"cats": {"Bills": 1.0}}),
    ("garbage collection", {"cats": {"Bills": 1.0}}),
    ("trash service", {"cats": {"Bills": 1.0}}),
    ("recycling fee", {"cats": {"Bills": 1.0}}),
    ("heating bill", {"cats": {"Bills": 1.0}}),
    ("cooling bill", {"cats": {"Bills": 1.0}}),
    ("HVAC service", {"cats": {"Bills": 1.0}}),
    ("electricity connection fee", {"cats": {"Bills": 1.0}}),
    ("water connection fee", {"cats": {"Bills": 1.0}}),
    ("gas connection fee", {"cats": {"Bills": 1.0}}),
    ("internet installation", {"cats": {"Bills": 1.0}}),
    ("cable installation", {"cats": {"Bills": 1.0}}),
    ("utility deposit", {"cats": {"Bills": 1.0}}),
    ("security deposit", {"cats": {"Bills": 1.0}}),
    ("late payment fee", {"cats": {"Bills": 1.0}}),
    ("reconnection fee", {"cats": {"Bills": 1.0}}),
    ("bill payment service", {"cats": {"Bills": 1.0}}),
    ("auto-pay setup", {"cats": {"Bills": 1.0}}),
    ("direct debit", {"cats": {"Bills": 1.0}}),
    ("standing order", {"cats": {"Bills": 1.0}}),
    ("bank fee", {"cats": {"Bills": 1.0}}),
    ("ATM fee", {"cats": {"Bills": 1.0}}),
    ("overdraft fee", {"cats": {"Bills": 1.0}}),
    ("transfer fee", {"cats": {"Bills": 1.0}}),
    ("foreign transaction fee", {"cats": {"Bills": 1.0}}),
    ("credit card annual fee", {"cats": {"Bills": 1.0}}),
    ("credit card interest", {"cats": {"Bills": 1.0}}),
    ("credit card minimum payment", {"cats": {"Bills": 1.0}}),
    ("credit card late fee", {"cats": {"Bills": 1.0}}),
    ("loan payment", {"cats": {"Bills": 1.0}}),
    ("student loan payment", {"cats": {"Bills": 1.0}}),
    ("car loan payment", {"cats": {"Bills": 1.0}}),
    ("personal loan payment", {"cats": {"Bills": 1.0}}),
    ("loan origination fee", {"cats": {"Bills": 1.0}}),
    ("loan interest", {"cats": {"Bills": 1.0}}),
    ("insurance premium", {"cats": {"Bills": 1.0}}),
    ("health insurance", {"cats": {"Bills": 1.0}}),
    ("car insurance", {"cats": {"Bills": 1.0}}),
    ("home insurance", {"cats": {"Bills": 1.0}}),
    ("renters insurance", {"cats": {"Bills": 1.0}}),
    ("life insurance", {"cats": {"Bills": 1.0}}),
    ("dental insurance", {"cats": {"Bills": 1.0}}),
    ("vision insurance", {"cats": {"Bills": 1.0}}),
    ("pet insurance", {"cats": {"Bills": 1.0}}),
    ("travel insurance", {"cats": {"Bills": 1.0}}),
    ("insurance deductible", {"cats": {"Bills": 1.0}}),
    ("insurance copay", {"cats": {"Bills": 1.0}}),
    ("doctor visit", {"cats": {"Bills": 1.0}}),
    ("specialist visit", {"cats": {"Bills": 1.0}}),
    ("hospital bill", {"cats": {"Bills": 1.0}}),
    ("emergency room", {"cats": {"Bills": 1.0}}),
    ("ambulance service", {"cats": {"Bills": 1.0}}),
    ("dental bill", {"cats": {"Bills": 1.0}}),
    ("prescription medication", {"cats": {"Bills": 1.0}}),
    ("veterinary bill", {"cats": {"Bills": 1.0}}),
    ("pet medication", {"cats": {"Bills": 1.0}}),
    ("tax payment", {"cats": {"Bills": 1.0}}),
    ("income tax", {"cats": {"Bills": 1.0}}),
    ("property tax", {"cats": {"Bills": 1.0}}),
    ("sales tax", {"cats": {"Bills": 1.0}}),
    ("tax preparation fee", {"cats": {"Bills": 1.0}}),
    ("accountant fee", {"cats": {"Bills": 1.0}}),
    ("legal fee", {"cats": {"Bills": 1.0}}),
    ("attorney fee", {"cats": {"Bills": 1.0}}),
    ("consultation fee", {"cats": {"Bills": 1.0}}),
    ("registration fee", {"cats": {"Bills": 1.0}}),
    ("license renewal", {"cats": {"Bills": 1.0}}),
    ("driver's license renewal", {"cats": {"Bills": 1.0}}),
    ("vehicle registration", {"cats": {"Bills": 1.0}}),
    ("parking permit", {"cats": {"Bills": 1.0}}),
    ("business license", {"cats": {"Bills": 1.0}}),
    ("professional license", {"cats": {"Bills": 1.0}}),
    ("certification fee", {"cats": {"Bills": 1.0}}),
    ("membership fee", {"cats": {"Bills": 1.0}}),
    ("club dues", {"cats": {"Bills": 1.0}}),
    ("gym membership", {"cats": {"Bills": 1.0}}),
    ("fitness center fee", {"cats": {"Bills": 1.0}}),
    ("subscription service", {"cats": {"Bills": 1.0}}),
    ("streaming service", {"cats": {"Bills": 1.0}}),
    ("Netflix subscription", {"cats": {"Bills": 1.0}}),
    ("Spotify subscription", {"cats": {"Bills": 1.0}}),
    ("Disney+ subscription", {"cats": {"Bills": 1.0}}),
    ("Amazon Prime membership", {"cats": {"Bills": 1.0}}),
    ("magazine subscription", {"cats": {"Bills": 1.0}}),
    ("newspaper subscription", {"cats": {"Bills": 1.0}}),
    ("software subscription", {"cats": {"Bills": 1.0}}),
    ("cloud storage fee", {"cats": {"Bills": 1.0}}),
    ("website hosting fee", {"cats": {"Bills": 1.0}}),
    ("domain registration", {"cats": {"Bills": 1.0}}),
    ("email service", {"cats": {"Bills": 1.0}}),
    ("VPN service", {"cats": {"Bills": 1.0}}),
    ("security system monitoring", {"cats": {"Bills": 1.0}}),
    ("alarm service", {"cats": {"Bills": 1.0}}),
    ("home warranty", {"cats": {"Bills": 1.0}}),
    ("appliance protection plan", {"cats": {"Bills": 1.0}}),
    ("extended warranty", {"cats": {"Bills": 1.0}}),
    ("education tuition", {"cats": {"Bills": 1.0}}),
    ("school fee", {"cats": {"Bills": 1.0}}),
    ("course registration", {"cats": {"Bills": 1.0}}),
    ("textbook purchase", {"cats": {"Bills": 1.0}}),
    ("childcare payment", {"cats": {"Bills": 1.0}}),
    ("daycare fee", {"cats": {"Bills": 1.0}}),
    ("babysitting service", {"cats": {"Bills": 1.0}}),
    ("elder care service", {"cats": {"Bills": 1.0}}),
    ("nursing home payment", {"cats": {"Bills": 1.0}}),
    ("assisted living fee", {"cats": {"Bills": 1.0}}),
    ("home maintenance service", {"cats": {"Bills": 1.0}}),
    ("lawn care service", {"cats": {"Bills": 1.0}}),
    ("snow removal service", {"cats": {"Bills": 1.0}}),
    ("cleaning service", {"cats": {"Bills": 1.0}}),

    # MEDICAL CATEGORY (100 examples)
    ("aspirin", {"cats": {"Medical": 1.0}}),
    ("acetaminophen", {"cats": {"Medical": 1.0}}),
    ("ibuprofen", {"cats": {"Medical": 1.0}}),
    ("amoxicillin", {"cats": {"Medical": 1.0}}),
    ("lisinopril", {"cats": {"Medical": 1.0}}),
    ("metformin", {"cats": {"Medical": 1.0}}),
    ("atorvastatin", {"cats": {"Medical": 1.0}}),
    ("levothyroxine", {"cats": {"Medical": 1.0}}),
    ("amlodipine", {"cats": {"Medical": 1.0}}),
    ("metoprolol", {"cats": {"Medical": 1.0}}),
    ("losartan", {"cats": {"Medical": 1.0}}),
    ("omeprazole", {"cats": {"Medical": 1.0}}),
    ("simvastatin", {"cats": {"Medical": 1.0}}),
    ("hydrochlorothiazide", {"cats": {"Medical": 1.0}}),
    ("gabapentin", {"cats": {"Medical": 1.0}}),
    ("sertraline", {"cats": {"Medical": 1.0}}),
    ("prednisone", {"cats": {"Medical": 1.0}}),
    ("fluoxetine", {"cats": {"Medical": 1.0}}),
    ("escitalopram", {"cats": {"Medical": 1.0}}),
    ("citalopram", {"cats": {"Medical": 1.0}}),
    ("fluticasone", {"cats": {"Medical": 1.0}}),
    ("albuterol", {"cats": {"Medical": 1.0}}),
    ("furosemide", {"cats": {"Medical": 1.0}}),
    ("warfarin", {"cats": {"Medical": 1.0}}),
    ("alprazolam", {"cats": {"Medical": 1.0}}),
    ("tramadol", {"cats": {"Medical": 1.0}}),
    ("montelukast", {"cats": {"Medical": 1.0}}),
    ("duloxetine", {"cats": {"Medical": 1.0}}),
    ("pantoprazole", {"cats": {"Medical": 1.0}}),
    ("venlafaxine", {"cats": {"Medical": 1.0}}),
    ("rosuvastatin", {"cats": {"Medical": 1.0}}),
    ("clonazepam", {"cats": {"Medical": 1.0}}),
    ("trazodone", {"cats": {"Medical": 1.0}}),
    ("carvedilol", {"cats": {"Medical": 1.0}}),
    ("azithromycin", {"cats": {"Medical": 1.0}}),
    ("cephalexin", {"cats": {"Medical": 1.0}}),
    ("bupropion", {"cats": {"Medical": 1.0}}),
    ("methylphenidate", {"cats": {"Medical": 1.0}}),
    ("lorazepam", {"cats": {"Medical": 1.0}}),
    ("pravastatin", {"cats": {"Medical": 1.0}}),
    ("ciprofloxacin", {"cats": {"Medical": 1.0}}),
    ("oxycodone", {"cats": {"Medical": 1.0}}),
    ("cyclobenzaprine", {"cats": {"Medical": 1.0}}),
    ("meloxicam", {"cats": {"Medical": 1.0}}),
    ("doxycycline", {"cats": {"Medical": 1.0}}),
    ("diazepam", {"cats": {"Medical": 1.0}}),
    ("amitriptyline", {"cats": {"Medical": 1.0}}),
    ("clopidogrel", {"cats": {"Medical": 1.0}}),
    ("naproxen", {"cats": {"Medical": 1.0}}),
    ("clindamycin", {"cats": {"Medical": 1.0}}),
    ("valsartan", {"cats": {"Medical": 1.0}}),
    ("ranitidine", {"cats": {"Medical": 1.0}}),
    ("dexamethasone", {"cats": {"Medical": 1.0}}),
    ("hydrocodone", {"cats": {"Medical": 1.0}}),
    ("sumatriptan", {"cats": {"Medical": 1.0}}),
    ("propranolol", {"cats": {"Medical": 1.0}}),
    ("fexofenadine", {"cats": {"Medical": 1.0}}),
    ("cetirizine", {"cats": {"Medical": 1.0}}),
    ("loratadine", {"cats": {"Medical": 1.0}}),
    ("paroxetine", {"cats": {"Medical": 1.0}}),
    ("glipizide", {"cats": {"Medical": 1.0}}),
    ("diltiazem", {"cats": {"Medical": 1.0}}),
    ("pregabalin", {"cats": {"Medical": 1.0}}),
    ("budesonide", {"cats": {"Medical": 1.0}}),
    ("spironolactone", {"cats": {"Medical": 1.0}}),
    ("mirtazapine", {"cats": {"Medical": 1.0}}),
    ("quetiapine", {"cats": {"Medical": 1.0}}),
    ("ondansetron", {"cats": {"Medical": 1.0}}),
    ("atenolol", {"cats": {"Medical": 1.0}}),
    ("famotidine", {"cats": {"Medical": 1.0}}),
    ("triamterene", {"cats": {"Medical": 1.0}}),
    ("digoxin", {"cats": {"Medical": 1.0}}),
    ("benazepril", {"cats": {"Medical": 1.0}}),
    ("insulin", {"cats": {"Medical": 1.0}}),
    ("celecoxib", {"cats": {"Medical": 1.0}}),
    ("ketoconazole", {"cats": {"Medical": 1.0}}),
    ("gemfibrozil", {"cats": {"Medical": 1.0}}),
    ("oxcarbazepine", {"cats": {"Medical": 1.0}}),
    ("nortriptyline", {"cats": {"Medical": 1.0}}),
    ("olanzapine", {"cats": {"Medical": 1.0}}),
    ("risperidone", {"cats": {"Medical": 1.0}}),
    ("hydroxyzine", {"cats": {"Medical": 1.0}}),
    ("lamotrigine", {"cats": {"Medical": 1.0}}),
    ("enalapril", {"cats": {"Medical": 1.0}}),
    ("clonidine", {"cats": {"Medical": 1.0}}),
    ("tamsulosin", {"cats": {"Medical": 1.0}}),
    ("latanoprost", {"cats": {"Medical": 1.0}}),
    ("sildenafil", {"cats": {"Medical": 1.0}}),
    ("finasteride", {"cats": {"Medical": 1.0}}),
    ("levetiracetam", {"cats": {"Medical": 1.0}}),
    ("phenytoin", {"cats": {"Medical": 1.0}}),
    ("lansoprazole", {"cats": {"Medical": 1.0}}),
    ("aripiprazole", {"cats": {"Medical": 1.0}}),
    ("topiramate", {"cats": {"Medical": 1.0}}),
    ("valacyclovir", {"cats": {"Medical": 1.0}}),
    ("acyclovir", {"cats": {"Medical": 1.0}}),
    ("metronidazole", {"cats": {"Medical": 1.0}}),
    ("rivaroxaban", {"cats": {"Medical": 1.0}}),
    ("apixaban", {"cats": {"Medical": 1.0}}),

    # CLOTHES CATEGORY (100 examples)
    ("t-shirt", {"cats": {"Clothes": 1.0}}),
    ("jeans", {"cats": {"Clothes": 1.0}}),
    ("sweater", {"cats": {"Clothes": 1.0}}),
    ("dress", {"cats": {"Clothes": 1.0}}),
    ("jacket", {"cats": {"Clothes": 1.0}}),
    ("coat", {"cats": {"Clothes": 1.0}}),
    ("blouse", {"cats": {"Clothes": 1.0}}),
    ("skirt", {"cats": {"Clothes": 1.0}}),
    ("shorts", {"cats": {"Clothes": 1.0}}),
    ("pants", {"cats": {"Clothes": 1.0}}),
    ("hoodie", {"cats": {"Clothes": 1.0}}),
    ("socks", {"cats": {"Clothes": 1.0}}),
    ("underwear", {"cats": {"Clothes": 1.0}}),
    ("bra", {"cats": {"Clothes": 1.0}}),
    ("cardigan", {"cats": {"Clothes": 1.0}}),
    ("sweatpants", {"cats": {"Clothes": 1.0}}),
    ("sweatshirt", {"cats": {"Clothes": 1.0}}),
    ("leggings", {"cats": {"Clothes": 1.0}}),
    ("suit", {"cats": {"Clothes": 1.0}}),
    ("blazer", {"cats": {"Clothes": 1.0}}),
    ("tank top", {"cats": {"Clothes": 1.0}}),
    ("turtleneck", {"cats": {"Clothes": 1.0}}),
    ("polo shirt", {"cats": {"Clothes": 1.0}}),
    ("vest", {"cats": {"Clothes": 1.0}}),
    ("flannel", {"cats": {"Clothes": 1.0}}),
    ("button-up shirt", {"cats": {"Clothes": 1.0}}),
    ("romper", {"cats": {"Clothes": 1.0}}),
    ("jumpsuit", {"cats": {"Clothes": 1.0}}),
    ("pajamas", {"cats": {"Clothes": 1.0}}),
    ("bathrobe", {"cats": {"Clothes": 1.0}}),
    ("swimsuit", {"cats": {"Clothes": 1.0}}),
    ("bikini", {"cats": {"Clothes": 1.0}}),
    ("swim trunks", {"cats": {"Clothes": 1.0}}),
    ("boxers", {"cats": {"Clothes": 1.0}}),
    ("briefs", {"cats": {"Clothes": 1.0}}),
    ("gloves", {"cats": {"Clothes": 1.0}}),
    ("mittens", {"cats": {"Clothes": 1.0}}),
    ("scarf", {"cats": {"Clothes": 1.0}}),
    ("hat", {"cats": {"Clothes": 1.0}}),
    ("beanie", {"cats": {"Clothes": 1.0}}),
    ("cap", {"cats": {"Clothes": 1.0}}),
    ("belt", {"cats": {"Clothes": 1.0}}),
    ("tie", {"cats": {"Clothes": 1.0}}),
    ("bow tie", {"cats": {"Clothes": 1.0}}),
    ("pantyhose", {"cats": {"Clothes": 1.0}}),
    ("stockings", {"cats": {"Clothes": 1.0}}),
    ("tights", {"cats": {"Clothes": 1.0}}),
    ("overalls", {"cats": {"Clothes": 1.0}}),
    ("raincoat", {"cats": {"Clothes": 1.0}}),
    ("windbreaker", {"cats": {"Clothes": 1.0}}),
    ("poncho", {"cats": {"Clothes": 1.0}}),
    ("trench coat", {"cats": {"Clothes": 1.0}}),
    ("parka", {"cats": {"Clothes": 1.0}}),
    ("shawl", {"cats": {"Clothes": 1.0}}),
    ("cape", {"cats": {"Clothes": 1.0}}),
    ("robe", {"cats": {"Clothes": 1.0}}),
    ("nightgown", {"cats": {"Clothes": 1.0}}),
    ("lingerie", {"cats": {"Clothes": 1.0}}),
    ("corset", {"cats": {"Clothes": 1.0}}),
    ("suspenders", {"cats": {"Clothes": 1.0}}),
    ("cufflinks", {"cats": {"Clothes": 1.0}}),
    ("crop top", {"cats": {"Clothes": 1.0}}),
    ("sleeveless shirt", {"cats": {"Clothes": 1.0}}),
    ("camisole", {"cats": {"Clothes": 1.0}}),
    ("bodysuit", {"cats": {"Clothes": 1.0}}),
    ("tunic", {"cats": {"Clothes": 1.0}}),
    ("kilt", {"cats": {"Clothes": 1.0}}),
    ("sarong", {"cats": {"Clothes": 1.0}}),
    ("kimono", {"cats": {"Clothes": 1.0}}),
    ("sari", {"cats": {"Clothes": 1.0}}),
    ("cheongsam", {"cats": {"Clothes": 1.0}}),
    ("dashiki", {"cats": {"Clothes": 1.0}}),
    ("dirndl", {"cats": {"Clothes": 1.0}}),
    ("lederhosen", {"cats": {"Clothes": 1.0}}),
    ("caftan", {"cats": {"Clothes": 1.0}}),
    ("poncho", {"cats": {"Clothes": 1.0}}),
    ("gown", {"cats": {"Clothes": 1.0}}),
    ("cloak", {"cats": {"Clothes": 1.0}}),
    ("tracksuit", {"cats": {"Clothes": 1.0}}),
    ("wetsuit", {"cats": {"Clothes": 1.0}}),
    ("denim jacket", {"cats": {"Clothes": 1.0}}),
    ("leather jacket", {"cats": {"Clothes": 1.0}}),
    ("puffer jacket", {"cats": {"Clothes": 1.0}}),
    ("peacoat", {"cats": {"Clothes": 1.0}}),
    ("cardigan", {"cats": {"Clothes": 1.0}}),
    ("dressing gown", {"cats": {"Clothes": 1.0}}),
    ("waistcoat", {"cats": {"Clothes": 1.0}}),
    ("dungarees", {"cats": {"Clothes": 1.0}}),
    ("pinafore", {"cats": {"Clothes": 1.0}}),
    ("uniform", {"cats": {"Clothes": 1.0}}),
    ("onesie", {"cats": {"Clothes": 1.0}}),
    ("hosiery", {"cats": {"Clothes": 1.0}}),
    ("bandana", {"cats": {"Clothes": 1.0}}),
    ("apron", {"cats": {"Clothes": 1.0}}),
    ("peplum top", {"cats": {"Clothes": 1.0}}),
    ("culottes", {"cats": {"Clothes": 1.0}}),
    ("pencil skirt", {"cats": {"Clothes": 1.0}}),
    ("pleated skirt", {"cats": {"Clothes": 1.0}}),
    ("cargo pants", {"cats": {"Clothes": 1.0}}),

    # PHONE CATEGORY (100 examples)
    ("iPhone", {"cats": {"Phone": 1.0}}),
    ("Samsung Galaxy", {"cats": {"Phone": 1.0}}),
    ("Google Pixel", {"cats": {"Phone": 1.0}}),
    ("OnePlus", {"cats": {"Phone": 1.0}}),
    ("Xiaomi", {"cats": {"Phone": 1.0}}),
    ("Motorola", {"cats": {"Phone": 1.0}}),
    ("Nokia", {"cats": {"Phone": 1.0}}),
    ("LG", {"cats": {"Phone": 1.0}}),
    ("Sony Xperia", {"cats": {"Phone": 1.0}}),
    ("HTC", {"cats": {"Phone": 1.0}}),
    ("Huawei", {"cats": {"Phone": 1.0}}),
    ("OPPO", {"cats": {"Phone": 1.0}}),
    ("Vivo", {"cats": {"Phone": 1.0}}),
    ("Realme", {"cats": {"Phone": 1.0}}),
    ("ASUS", {"cats": {"Phone": 1.0}}),
    ("BlackBerry", {"cats": {"Phone": 1.0}}),
    ("ZTE", {"cats": {"Phone": 1.0}}),
    ("Honor", {"cats": {"Phone": 1.0}}),
    ("Nothing Phone", {"cats": {"Phone": 1.0}}),
    ("Poco", {"cats": {"Phone": 1.0}}),
    ("smartphone", {"cats": {"Phone": 1.0}}),
    ("feature phone", {"cats": {"Phone": 1.0}}),
    ("flip phone", {"cats": {"Phone": 1.0}}),
    ("foldable phone", {"cats": {"Phone": 1.0}}),
    ("touchscreen", {"cats": {"Phone": 1.0}}),
    ("keypad", {"cats": {"Phone": 1.0}}),
    ("speakerphone", {"cats": {"Phone": 1.0}}),
    ("camera phone", {"cats": {"Phone": 1.0}}),
    ("battery", {"cats": {"Phone": 1.0}}),
    ("charger", {"cats": {"Phone": 1.0}}),
    ("charging cable", {"cats": {"Phone": 1.0}}),
    ("power adapter", {"cats": {"Phone": 1.0}}),
    ("wireless charger", {"cats": {"Phone": 1.0}}),
    ("car charger", {"cats": {"Phone": 1.0}}),
    ("screen protector", {"cats": {"Phone": 1.0}}),
    ("phone case", {"cats": {"Phone": 1.0}}),
    ("screen", {"cats": {"Phone": 1.0}}),
    ("LCD display", {"cats": {"Phone": 1.0}}),
    ("OLED display", {"cats": {"Phone": 1.0}}),
    ("front camera", {"cats": {"Phone": 1.0}}),
    ("rear camera", {"cats": {"Phone": 1.0}}),
    ("flash", {"cats": {"Phone": 1.0}}),
    ("selfie stick", {"cats": {"Phone": 1.0}}),
    ("SIM card", {"cats": {"Phone": 1.0}}),
    ("eSIM", {"cats": {"Phone": 1.0}}),
    ("memory card", {"cats": {"Phone": 1.0}}),
    ("microSD", {"cats": {"Phone": 1.0}}),
    ("headphone jack", {"cats": {"Phone": 1.0}}),
    ("USB port", {"cats": {"Phone": 1.0}}),
    ("Lightning port", {"cats": {"Phone": 1.0}}),
    ("USB-C port", {"cats": {"Phone": 1.0}}),
    ("microphone", {"cats": {"Phone": 1.0}}),
    ("speaker", {"cats": {"Phone": 1.0}}),
    ("earpiece", {"cats": {"Phone": 1.0}}),
    ("fingerprint sensor", {"cats": {"Phone": 1.0}}),
    ("face recognition", {"cats": {"Phone": 1.0}}),
    ("processor", {"cats": {"Phone": 1.0}}),
    ("RAM", {"cats": {"Phone": 1.0}}),
    ("storage", {"cats": {"Phone": 1.0}}),
    ("operating system", {"cats": {"Phone": 1.0}}),
    ("Android", {"cats": {"Phone": 1.0}}),
    ("iOS", {"cats": {"Phone": 1.0}}),
    ("5G", {"cats": {"Phone": 1.0}}),
    ("4G", {"cats": {"Phone": 1.0}}),
    ("LTE", {"cats": {"Phone": 1.0}}),
    ("Wi-Fi", {"cats": {"Phone": 1.0}}),
    ("Bluetooth", {"cats": {"Phone": 1.0}}),
    ("NFC", {"cats": {"Phone": 1.0}}),
    ("GPS", {"cats": {"Phone": 1.0}}),
    ("mobile data", {"cats": {"Phone": 1.0}}),
    ("roaming", {"cats": {"Phone": 1.0}}),
    ("voicemail", {"cats": {"Phone": 1.0}}),
    ("call waiting", {"cats": {"Phone": 1.0}}),
    ("caller ID", {"cats": {"Phone": 1.0}}),
    ("text message", {"cats": {"Phone": 1.0}}),
    ("SMS", {"cats": {"Phone": 1.0}}),
    ("MMS", {"cats": {"Phone": 1.0}}),
    ("ringtone", {"cats": {"Phone": 1.0}}),
    ("vibration", {"cats": {"Phone": 1.0}}),
    ("silent mode", {"cats": {"Phone": 1.0}}),
    ("airplane mode", {"cats": {"Phone": 1.0}}),
    ("do not disturb", {"cats": {"Phone": 1.0}}),
    ("app store", {"cats": {"Phone": 1.0}}),
    ("play store", {"cats": {"Phone": 1.0}}),
    ("contacts", {"cats": {"Phone": 1.0}}),
    ("phone number", {"cats": {"Phone": 1.0}}),
    ("dialer", {"cats": {"Phone": 1.0}}),
    ("call log", {"cats": {"Phone": 1.0}}),
    ("address book", {"cats": {"Phone": 1.0}}),
    ("video call", {"cats": {"Phone": 1.0}}),
    ("phablet", {"cats": {"Phone": 1.0}}),
    ("mobile phone", {"cats": {"Phone": 1.0}}),
    ("cell phone", {"cats": {"Phone": 1.0}}),
    ("handset", {"cats": {"Phone": 1.0}}),
    ("unlocked phone", {"cats": {"Phone": 1.0}}),
    ("refurbished phone", {"cats": {"Phone": 1.0}}),
    ("brick phone", {"cats": {"Phone": 1.0}}),
    ("clamshell phone", {"cats": {"Phone": 1.0}}),
    ("slider phone", {"cats": {"Phone": 1.0}}),
    ("rotary phone", {"cats": {"Phone": 1.0}}),

    ("gym membership", {"cats": {"Sport": 1.0}}),
    ("personal trainer", {"cats": {"Sport": 1.0}}),
    ("sports equipment", {"cats": {"Sport": 1.0}}),
    ("tennis racket", {"cats": {"Sport": 1.0}}),
    ("running shoes", {"cats": {"Sport": 1.0}}),
    ("basketball", {"cats": {"Sport": 1.0}}),
    ("football", {"cats": {"Sport": 1.0}}),
    ("soccer cleats", {"cats": {"Sport": 1.0}}),
    ("swimming goggles", {"cats": {"Sport": 1.0}}),
    ("swimsuit", {"cats": {"Sport": 1.0}}),
    ("swim cap", {"cats": {"Sport": 1.0}}),
    ("hockey stick", {"cats": {"Sport": 1.0}}),
    ("hockey skates", {"cats": {"Sport": 1.0}}),
    ("boxing gloves", {"cats": {"Sport": 1.0}}),
    ("punching bag", {"cats": {"Sport": 1.0}}),
    ("sports jersey", {"cats": {"Sport": 1.0}}),
    ("weightlifting belt", {"cats": {"Sport": 1.0}}),
    ("dumbbells", {"cats": {"Sport": 1.0}}),
    ("treadmill", {"cats": {"Sport": 1.0}}),
    ("exercise bike", {"cats": {"Sport": 1.0}}),
    ("rowing machine", {"cats": {"Sport": 1.0}}),
    ("elliptical trainer", {"cats": {"Sport": 1.0}}),
    ("yoga mat", {"cats": {"Sport": 1.0}}),
    ("yoga class", {"cats": {"Sport": 1.0}}),
    ("pilates class", {"cats": {"Sport": 1.0}}),
    ("sports massage", {"cats": {"Sport": 1.0}}),
    ("golf clubs", {"cats": {"Sport": 1.0}}),
    ("golf balls", {"cats": {"Sport": 1.0}}),
    ("golf tee time", {"cats": {"Sport": 1.0}}),
    ("golf cart rental", {"cats": {"Sport": 1.0}}),
    ("ski equipment", {"cats": {"Sport": 1.0}}),
    ("ski lift tickets", {"cats": {"Sport": 1.0}}),
    ("ski resort fees", {"cats": {"Sport": 1.0}}),
    ("snowboard", {"cats": {"Sport": 1.0}}),
    ("hiking boots", {"cats": {"Sport": 1.0}}),
    ("camping gear", {"cats": {"Sport": 1.0}}),
    ("tent", {"cats": {"Sport": 1.0}}),
    ("climbing gear", {"cats": {"Sport": 1.0}}),
    ("rock climbing gym", {"cats": {"Sport": 1.0}}),
    ("surfboard", {"cats": {"Sport": 1.0}}),
    ("wetsuit", {"cats": {"Sport": 1.0}}),
    ("kayak", {"cats": {"Sport": 1.0}}),
    ("kayak rental", {"cats": {"Sport": 1.0}}),
    ("fishing rod", {"cats": {"Sport": 1.0}}),
    ("fishing license", {"cats": {"Sport": 1.0}}),
    ("fishing bait", {"cats": {"Sport": 1.0}}),
    ("sports tournament fees", {"cats": {"Sport": 1.0}}),
    ("marathon registration", {"cats": {"Sport": 1.0}}),
    ("race entry fee", {"cats": {"Sport": 1.0}}),
    ("sports team membership", {"cats": {"Sport": 1.0}}),
    ("baseball bat", {"cats": {"Sport": 1.0}}),
    ("baseball glove", {"cats": {"Sport": 1.0}}),
    ("baseball cleats", {"cats": {"Sport": 1.0}}),
    ("sports nutrition", {"cats": {"Sport": 1.0}}),
    ("protein powder", {"cats": {"Sport": 1.0}}),
    ("energy bars", {"cats": {"Sport": 1.0}}),
    ("sports drinks", {"cats": {"Sport": 1.0}}),
    ("electrolyte supplements", {"cats": {"Sport": 1.0}}),
    ("sports injury treatment", {"cats": {"Sport": 1.0}}),
    ("physical therapy", {"cats": {"Sport": 1.0}}),
    ("knee brace", {"cats": {"Sport": 1.0}}),
    ("ankle support", {"cats": {"Sport": 1.0}}),
    ("compression sleeve", {"cats": {"Sport": 1.0}}),
    ("ice pack", {"cats": {"Sport": 1.0}}),
    ("sports tape", {"cats": {"Sport": 1.0}}),
    ("fitness tracker", {"cats": {"Sport": 1.0}}),
    ("heart rate monitor", {"cats": {"Sport": 1.0}}),
    ("sports watch", {"cats": {"Sport": 1.0}}),
    ("sports app subscription", {"cats": {"Sport": 1.0}}),
    ("cycling helmet", {"cats": {"Sport": 1.0}}),
    ("bicycle", {"cats": {"Sport": 1.0}}),
    ("bicycle repair", {"cats": {"Sport": 1.0}}),
    ("bicycle parts", {"cats": {"Sport": 1.0}}),
    ("tennis court rental", {"cats": {"Sport": 1.0}}),
    ("badminton court rental", {"cats": {"Sport": 1.0}}),
    ("squash court rental", {"cats": {"Sport": 1.0}}),
    ("bowling lane rental", {"cats": {"Sport": 1.0}}),
    ("bowling shoes rental", {"cats": {"Sport": 1.0}}),
    ("sports fan merchandise", {"cats": {"Sport": 1.0}}),
    ("stadium tickets", {"cats": {"Sport": 1.0}}),
    ("sports channel subscription", {"cats": {"Sport": 1.0}}),
    ("sports streaming service", {"cats": {"Sport": 1.0}}),
    ("sports betting", {"cats": {"Sport": 1.0}}),
    ("sports fantasy league", {"cats": {"Sport": 1.0}}),
    ("dance class", {"cats": {"Sport": 1.0}}),
    ("martial arts class", {"cats": {"Sport": 1.0}}),
    ("karate uniform", {"cats": {"Sport": 1.0}}),
    ("belt promotion test fee", {"cats": {"Sport": 1.0}}),
    ("crossfit membership", {"cats": {"Sport": 1.0}}),
    ("sports medical checkup", {"cats": {"Sport": 1.0}}),
    ("sports insurance", {"cats": {"Sport": 1.0}}),
    ("sports travel expenses", {"cats": {"Sport": 1.0}}),
    ("sports training camp", {"cats": {"Sport": 1.0}}),
    ("sports coaching", {"cats": {"Sport": 1.0}}),
    ("swimming pool membership", {"cats": {"Sport": 1.0}}),
    ("athletic tape", {"cats": {"Sport": 1.0}}),
    ("sports mouthguard", {"cats": {"Sport": 1.0}}),
    ("referee fee", {"cats": {"Sport": 1.0}}),
    ("sports field rental", {"cats": {"Sport": 1.0}}),
    ("sports photography", {"cats": {"Sport": 1.0}}),
    ("sports uniform", {"cats": {"Sport": 1.0}}),

    ("tuition", {"cats": {"Education": 1.0}}),
    ("textbooks", {"cats": {"Education": 1.0}}),
    ("school fees", {"cats": {"Education": 1.0}}),
    ("enrollment fee", {"cats": {"Education": 1.0}}),
    ("registration fee", {"cats": {"Education": 1.0}}),
    ("application fee", {"cats": {"Education": 1.0}}),
    ("college admission fee", {"cats": {"Education": 1.0}}),
    ("student housing", {"cats": {"Education": 1.0}}),
    ("dormitory fee", {"cats": {"Education": 1.0}}),
    ("meal plan", {"cats": {"Education": 1.0}}),
    ("cafeteria expenses", {"cats": {"Education": 1.0}}),
    ("online course", {"cats": {"Education": 1.0}}),
    ("course materials", {"cats": {"Education": 1.0}}),
    ("lab fee", {"cats": {"Education": 1.0}}),
    ("technology fee", {"cats": {"Education": 1.0}}),
    ("library fee", {"cats": {"Education": 1.0}}),
    ("student activity fee", {"cats": {"Education": 1.0}}),
    ("athletic fee", {"cats": {"Education": 1.0}}),
    ("health service fee", {"cats": {"Education": 1.0}}),
    ("graduation fee", {"cats": {"Education": 1.0}}),
    ("cap and gown", {"cats": {"Education": 1.0}}),
    ("diploma frame", {"cats": {"Education": 1.0}}),
    ("transcript fee", {"cats": {"Education": 1.0}}),
    ("certification exam fee", {"cats": {"Education": 1.0}}),
    ("professional license fee", {"cats": {"Education": 1.0}}),
    ("study abroad program", {"cats": {"Education": 1.0}}),
    ("internship fee", {"cats": {"Education": 1.0}}),
    ("student insurance", {"cats": {"Education": 1.0}}),
    ("school supplies", {"cats": {"Education": 1.0}}),
    ("notebooks", {"cats": {"Education": 1.0}}),
    ("pens", {"cats": {"Education": 1.0}}),
    ("pencils", {"cats": {"Education": 1.0}}),
    ("calculator", {"cats": {"Education": 1.0}}),
    ("backpack", {"cats": {"Education": 1.0}}),
    ("laptop", {"cats": {"Education": 1.0}}),
    ("computer software", {"cats": {"Education": 1.0}}),
    ("printer", {"cats": {"Education": 1.0}}),
    ("printer ink", {"cats": {"Education": 1.0}}),
    ("paper", {"cats": {"Education": 1.0}}),
    ("art supplies", {"cats": {"Education": 1.0}}),
    ("science project materials", {"cats": {"Education": 1.0}}),
    ("tutoring", {"cats": {"Education": 1.0}}),
    ("private lessons", {"cats": {"Education": 1.0}}),
    ("SAT prep course", {"cats": {"Education": 1.0}}),
    ("test preparation", {"cats": {"Education": 1.0}}),
    ("standardized test fee", {"cats": {"Education": 1.0}}),
    ("language learning app", {"cats": {"Education": 1.0}}),
    ("educational subscription", {"cats": {"Education": 1.0}}),
    ("research database access", {"cats": {"Education": 1.0}}),
    ("academic journal subscription", {"cats": {"Education": 1.0}}),
    ("student organization dues", {"cats": {"Education": 1.0}}),
    ("field trip", {"cats": {"Education": 1.0}}),
    ("educational travel", {"cats": {"Education": 1.0}}),
    ("school uniform", {"cats": {"Education": 1.0}}),
    ("music instrument rental", {"cats": {"Education": 1.0}}),
    ("sheet music", {"cats": {"Education": 1.0}}),
    ("specialized equipment", {"cats": {"Education": 1.0}}),
    ("safety equipment", {"cats": {"Education": 1.0}}),
    ("academic conference fee", {"cats": {"Education": 1.0}}),
    ("research expenses", {"cats": {"Education": 1.0}}),
    ("thesis printing", {"cats": {"Education": 1.0}}),
    ("dissertation binding", {"cats": {"Education": 1.0}}),
    ("student loan payment", {"cats": {"Education": 1.0}}),
    ("student loan interest", {"cats": {"Education": 1.0}}),
    ("student loan origination fee", {"cats": {"Education": 1.0}}),
    ("scholarship application fee", {"cats": {"Education": 1.0}}),
    ("financial aid counseling", {"cats": {"Education": 1.0}}),
    ("commuting expenses", {"cats": {"Education": 1.0}}),
    ("parking permit", {"cats": {"Education": 1.0}}),
    ("campus shuttle fee", {"cats": {"Education": 1.0}}),
    ("student ID replacement", {"cats": {"Education": 1.0}}),
    ("library late fee", {"cats": {"Education": 1.0}}),
    ("photocopying", {"cats": {"Education": 1.0}}),
    ("printing credit", {"cats": {"Education": 1.0}}),
    ("school photos", {"cats": {"Education": 1.0}}),
    ("yearbook", {"cats": {"Education": 1.0}}),
    ("class ring", {"cats": {"Education": 1.0}}),
    ("school fundraiser", {"cats": {"Education": 1.0}}),
    ("parent-teacher association fee", {"cats": {"Education": 1.0}}),
    ("school donation", {"cats": {"Education": 1.0}}),
    ("alumni association fee", {"cats": {"Education": 1.0}}),
    ("professional development", {"cats": {"Education": 1.0}}),
    ("continuing education", {"cats": {"Education": 1.0}}),
    ("workshop fee", {"cats": {"Education": 1.0}}),
    ("certificate program", {"cats": {"Education": 1.0}}),
    ("vocational training", {"cats": {"Education": 1.0}}),
    ("apprenticeship materials", {"cats": {"Education": 1.0}}),
    ("academic coaching", {"cats": {"Education": 1.0}}),
    ("educational assessment", {"cats": {"Education": 1.0}}),
    ("learning disability testing", {"cats": {"Education": 1.0}}),
    ("special education services", {"cats": {"Education": 1.0}}),
    ("homeschool curriculum", {"cats": {"Education": 1.0}}),
    ("homeschool supplies", {"cats": {"Education": 1.0}}),
    ("educational games", {"cats": {"Education": 1.0}}),
    ("educational software", {"cats": {"Education": 1.0}}),
    ("educational books", {"cats": {"Education": 1.0}}),
    ("reference materials", {"cats": {"Education": 1.0}}),
    ("language exchange program", {"cats": {"Education": 1.0}}),
    ("summer school", {"cats": {"Education": 1.0}}),
    ("after-school program", {"cats": {"Education": 1.0}}),

    ("haircut", {"cats": {"Beauty": 1.0}}),
    ("hair coloring", {"cats": {"Beauty": 1.0}}),
    ("highlights", {"cats": {"Beauty": 1.0}}),
    ("hair styling", {"cats": {"Beauty": 1.0}}),
    ("blowout", {"cats": {"Beauty": 1.0}}),
    ("hair extensions", {"cats": {"Beauty": 1.0}}),
    ("hair treatment", {"cats": {"Beauty": 1.0}}),
    ("keratin treatment", {"cats": {"Beauty": 1.0}}),
    ("hair products", {"cats": {"Beauty": 1.0}}),
    ("shampoo", {"cats": {"Beauty": 1.0}}),
    ("conditioner", {"cats": {"Beauty": 1.0}}),
    ("hair mask", {"cats": {"Beauty": 1.0}}),
    ("hair serum", {"cats": {"Beauty": 1.0}}),
    ("hair spray", {"cats": {"Beauty": 1.0}}),
    ("hair gel", {"cats": {"Beauty": 1.0}}),
    ("hair mousse", {"cats": {"Beauty": 1.0}}),
    ("leave-in conditioner", {"cats": {"Beauty": 1.0}}),
    ("heat protectant", {"cats": {"Beauty": 1.0}}),
    ("hair dryer", {"cats": {"Beauty": 1.0}}),
    ("curling iron", {"cats": {"Beauty": 1.0}}),
    ("straightener", {"cats": {"Beauty": 1.0}}),
    ("facial", {"cats": {"Beauty": 1.0}}),
    ("facial cleanser", {"cats": {"Beauty": 1.0}}),
    ("face moisturizer", {"cats": {"Beauty": 1.0}}),
    ("face serum", {"cats": {"Beauty": 1.0}}),
    ("face mask", {"cats": {"Beauty": 1.0}}),
    ("eye cream", {"cats": {"Beauty": 1.0}}),
    ("toner", {"cats": {"Beauty": 1.0}}),
    ("exfoliator", {"cats": {"Beauty": 1.0}}),
    ("microdermabrasion", {"cats": {"Beauty": 1.0}}),
    ("chemical peel", {"cats": {"Beauty": 1.0}}),
    ("anti-aging cream", {"cats": {"Beauty": 1.0}}),
    ("sunscreen", {"cats": {"Beauty": 1.0}}),
    ("makeup", {"cats": {"Beauty": 1.0}}),
    ("foundation", {"cats": {"Beauty": 1.0}}),
    ("concealer", {"cats": {"Beauty": 1.0}}),
    ("powder", {"cats": {"Beauty": 1.0}}),
    ("blush", {"cats": {"Beauty": 1.0}}),
    ("bronzer", {"cats": {"Beauty": 1.0}}),
    ("highlighter", {"cats": {"Beauty": 1.0}}),
    ("eyeshadow", {"cats": {"Beauty": 1.0}}),
    ("eyeliner", {"cats": {"Beauty": 1.0}}),
    ("mascara", {"cats": {"Beauty": 1.0}}),
    ("lipstick", {"cats": {"Beauty": 1.0}}),
    ("lip gloss", {"cats": {"Beauty": 1.0}}),
    ("lip liner", {"cats": {"Beauty": 1.0}}),
    ("makeup brushes", {"cats": {"Beauty": 1.0}}),
    ("makeup sponge", {"cats": {"Beauty": 1.0}}),
    ("makeup remover", {"cats": {"Beauty": 1.0}}),
    ("makeup setting spray", {"cats": {"Beauty": 1.0}}),
    ("eyebrow waxing", {"cats": {"Beauty": 1.0}}),
    ("eyebrow threading", {"cats": {"Beauty": 1.0}}),
    ("eyebrow tinting", {"cats": {"Beauty": 1.0}}),
    ("eyebrow pencil", {"cats": {"Beauty": 1.0}}),
    ("eyelash extensions", {"cats": {"Beauty": 1.0}}),
    ("eyelash lift", {"cats": {"Beauty": 1.0}}),
    ("eyelash curler", {"cats": {"Beauty": 1.0}}),
    ("manicure", {"cats": {"Beauty": 1.0}}),
    ("pedicure", {"cats": {"Beauty": 1.0}}),
    ("nail polish", {"cats": {"Beauty": 1.0}}),
    ("gel nails", {"cats": {"Beauty": 1.0}}),
    ("acrylic nails", {"cats": {"Beauty": 1.0}}),
    ("nail art", {"cats": {"Beauty": 1.0}}),
    ("nail tools", {"cats": {"Beauty": 1.0}}),
    ("cuticle oil", {"cats": {"Beauty": 1.0}}),
    ("nail polish remover", {"cats": {"Beauty": 1.0}}),
    ("waxing", {"cats": {"Beauty": 1.0}}),
    ("laser hair removal", {"cats": {"Beauty": 1.0}}),
    ("electrolysis", {"cats": {"Beauty": 1.0}}),
    ("threading", {"cats": {"Beauty": 1.0}}),
    ("shaving cream", {"cats": {"Beauty": 1.0}}),
    ("razor", {"cats": {"Beauty": 1.0}}),
    ("aftershave", {"cats": {"Beauty": 1.0}}),
    ("depilatory cream", {"cats": {"Beauty": 1.0}}),
    ("body scrub", {"cats": {"Beauty": 1.0}}),
    ("body lotion", {"cats": {"Beauty": 1.0}}),
    ("body oil", {"cats": {"Beauty": 1.0}}),
    ("body wash", {"cats": {"Beauty": 1.0}}),
    ("perfume", {"cats": {"Beauty": 1.0}}),
    ("cologne", {"cats": {"Beauty": 1.0}}),
    ("deodorant", {"cats": {"Beauty": 1.0}}),
    ("massage", {"cats": {"Beauty": 1.0}}),
    ("spa treatment", {"cats": {"Beauty": 1.0}}),
    ("spa day package", {"cats": {"Beauty": 1.0}}),
    ("sauna", {"cats": {"Beauty": 1.0}}),
    ("steam room", {"cats": {"Beauty": 1.0}}),
    ("tanning", {"cats": {"Beauty": 1.0}}),
    ("self-tanner", {"cats": {"Beauty": 1.0}}),
    ("spray tan", {"cats": {"Beauty": 1.0}}),
    ("teeth whitening", {"cats": {"Beauty": 1.0}}),
    ("whitening strips", {"cats": {"Beauty": 1.0}}),
    ("whitening toothpaste", {"cats": {"Beauty": 1.0}}),
    ("cosmetic dentistry", {"cats": {"Beauty": 1.0}}),
    ("dermatologist visit", {"cats": {"Beauty": 1.0}}),
    ("botox", {"cats": {"Beauty": 1.0}}),
    ("fillers", {"cats": {"Beauty": 1.0}}),
    ("cosmetic surgery", {"cats": {"Beauty": 1.0}}),
    ("makeup class", {"cats": {"Beauty": 1.0}}),
    ("skincare consultation", {"cats": {"Beauty": 1.0}}),
    ("beauty subscription box", {"cats": {"Beauty": 1.0}}),

    ("car purchase", {"cats": {"Vehicle": 1.0}}),
    ("down payment", {"cats": {"Vehicle": 1.0}}),
    ("car loan payment", {"cats": {"Vehicle": 1.0}}),
    ("car loan interest", {"cats": {"Vehicle": 1.0}}),
    ("used car", {"cats": {"Vehicle": 1.0}}),
    ("new car", {"cats": {"Vehicle": 1.0}}),
    ("motorcycle", {"cats": {"Vehicle": 1.0}}),
    ("scooter", {"cats": {"Vehicle": 1.0}}),
    ("bicycle", {"cats": {"Vehicle": 1.0}}),
    ("truck", {"cats": {"Vehicle": 1.0}}),
    ("SUV", {"cats": {"Vehicle": 1.0}}),
    ("van", {"cats": {"Vehicle": 1.0}}),
    ("RV", {"cats": {"Vehicle": 1.0}}),
    ("boat", {"cats": {"Vehicle": 1.0}}),
    ("ATV", {"cats": {"Vehicle": 1.0}}),
    ("snowmobile", {"cats": {"Vehicle": 1.0}}),
    ("jet ski", {"cats": {"Vehicle": 1.0}}),
    ("trailer", {"cats": {"Vehicle": 1.0}}),
    ("car registration", {"cats": {"Vehicle": 1.0}}),
    ("license plate fee", {"cats": {"Vehicle": 1.0}}),
    ("car title fee", {"cats": {"Vehicle": 1.0}}),
    ("driver's license", {"cats": {"Vehicle": 1.0}}),
    ("gasoline", {"cats": {"Vehicle": 1.0}}),
    ("diesel", {"cats": {"Vehicle": 1.0}}),
    ("electric charging", {"cats": {"Vehicle": 1.0}}),
    ("car insurance", {"cats": {"Vehicle": 1.0}}),
    ("motorcycle insurance", {"cats": {"Vehicle": 1.0}}),
    ("boat insurance", {"cats": {"Vehicle": 1.0}}),
    ("oil change", {"cats": {"Vehicle": 1.0}}),
    ("tire rotation", {"cats": {"Vehicle": 1.0}}),
    ("new tires", {"cats": {"Vehicle": 1.0}}),
    ("tire repair", {"cats": {"Vehicle": 1.0}}),
    ("brake repair", {"cats": {"Vehicle": 1.0}}),
    ("brake pads", {"cats": {"Vehicle": 1.0}}),
    ("transmission repair", {"cats": {"Vehicle": 1.0}}),
    ("transmission fluid", {"cats": {"Vehicle": 1.0}}),
    ("engine repair", {"cats": {"Vehicle": 1.0}}),
    ("timing belt", {"cats": {"Vehicle": 1.0}}),
    ("alternator", {"cats": {"Vehicle": 1.0}}),
    ("battery replacement", {"cats": {"Vehicle": 1.0}}),
    ("starter replacement", {"cats": {"Vehicle": 1.0}}),
    ("spark plugs", {"cats": {"Vehicle": 1.0}}),
    ("air filter", {"cats": {"Vehicle": 1.0}}),
    ("cabin filter", {"cats": {"Vehicle": 1.0}}),
    ("windshield wipers", {"cats": {"Vehicle": 1.0}}),
    ("windshield repair", {"cats": {"Vehicle": 1.0}}),
    ("headlight replacement", {"cats": {"Vehicle": 1.0}}),
    ("taillight replacement", {"cats": {"Vehicle": 1.0}}),
    ("bulb replacement", {"cats": {"Vehicle": 1.0}}),
    ("car wash", {"cats": {"Vehicle": 1.0}}),
    ("car detailing", {"cats": {"Vehicle": 1.0}}),
    ("car wax", {"cats": {"Vehicle": 1.0}}),
    ("car polish", {"cats": {"Vehicle": 1.0}}),
    ("air freshener", {"cats": {"Vehicle": 1.0}}),
    ("seat covers", {"cats": {"Vehicle": 1.0}}),
    ("floor mats", {"cats": {"Vehicle": 1.0}}),
    ("steering wheel cover", {"cats": {"Vehicle": 1.0}}),
    ("car accessories", {"cats": {"Vehicle": 1.0}}),
    ("GPS device", {"cats": {"Vehicle": 1.0}}),
    ("dash cam", {"cats": {"Vehicle": 1.0}}),
    ("phone mount", {"cats": {"Vehicle": 1.0}}),
    ("jumper cables", {"cats": {"Vehicle": 1.0}}),
    ("roadside assistance", {"cats": {"Vehicle": 1.0}}),
    ("towing service", {"cats": {"Vehicle": 1.0}}),
    ("parking fee", {"cats": {"Vehicle": 1.0}}),
    ("parking permit", {"cats": {"Vehicle": 1.0}}),
    ("garage rental", {"cats": {"Vehicle": 1.0}}),
    ("toll fee", {"cats": {"Vehicle": 1.0}}),
    ("toll pass", {"cats": {"Vehicle": 1.0}}),
    ("traffic ticket", {"cats": {"Vehicle": 1.0}}),
    ("parking ticket", {"cats": {"Vehicle": 1.0}}),
    ("emissions test", {"cats": {"Vehicle": 1.0}}),
    ("vehicle inspection", {"cats": {"Vehicle": 1.0}}),
    ("car rental", {"cats": {"Vehicle": 1.0}}),
    ("ride sharing", {"cats": {"Vehicle": 1.0}}),
    ("taxi fare", {"cats": {"Vehicle": 1.0}}),
    ("car shipping", {"cats": {"Vehicle": 1.0}}),
    ("vehicle storage", {"cats": {"Vehicle": 1.0}}),
    ("car alarm system", {"cats": {"Vehicle": 1.0}}),
    ("remote starter", {"cats": {"Vehicle": 1.0}}),
    ("wheel alignment", {"cats": {"Vehicle": 1.0}}),
    ("suspension repair", {"cats": {"Vehicle": 1.0}}),
    ("exhaust repair", {"cats": {"Vehicle": 1.0}}),
    ("muffler replacement", {"cats": {"Vehicle": 1.0}}),
    ("catalytic converter", {"cats": {"Vehicle": 1.0}}),
    ("radiator repair", {"cats": {"Vehicle": 1.0}}),
    ("coolant flush", {"cats": {"Vehicle": 1.0}}),
    ("antifreeze", {"cats": {"Vehicle": 1.0}}),
    ("power steering fluid", {"cats": {"Vehicle": 1.0}}),
    ("belt replacement", {"cats": {"Vehicle": 1.0}}),
    ("hose replacement", {"cats": {"Vehicle": 1.0}}),
    ("fuel pump", {"cats": {"Vehicle": 1.0}}),
    ("oxygen sensor", {"cats": {"Vehicle": 1.0}}),
    ("shock absorbers", {"cats": {"Vehicle": 1.0}}),
    ("struts", {"cats": {"Vehicle": 1.0}}),
    ("car paint job", {"cats": {"Vehicle": 1.0}}),
    ("body work", {"cats": {"Vehicle": 1.0}}),
    ("dent repair", {"cats": {"Vehicle": 1.0}}),
    ("window tinting", {"cats": {"Vehicle": 1.0}}),
    ("auto club membership", {"cats": {"Vehicle": 1.0}})
]

# You can use this enhanced training data to train your text classifier
# The balanced dataset provides 100 examples per category


# Split data into training and evaluation sets
train_data, eval_data = train_test_split(TRAINING_DATA, test_size=0.2, random_state=42)
print(f"Training examples: {len(train_data)}")
print(f"Evaluation examples: {len(eval_data)}")

# Training the model
n_iter = 30  # Increased iterations
optimizer = nlp.initialize()

# Training loop
for i in range(n_iter):
    random.shuffle(train_data)
    losses = {}
    batches = spacy.util.minibatch(train_data, size=8)  # Use batches for efficiency

    for batch in batches:
        examples = []
        for text, annotations in batch:
            doc = nlp.make_doc(text)
            example = Example.from_dict(doc, annotations)
            examples.append(example)

        nlp.update(examples, drop=0.2, losses=losses)  # Added dropout

    print(f"Iteration {i + 1}, Loss: {losses}")

# Evaluate on the test set
correct_predictions = 0
total_predictions = len(eval_data)

for text, annotations in eval_data:
    doc = nlp(text)
    predicted_category = max(doc.cats, key=doc.cats.get)
    true_category = max(annotations["cats"], key=annotations["cats"].get)

    if predicted_category == true_category:
        correct_predictions += 1

accuracy = correct_predictions / total_predictions
print(f"Model accuracy on evaluation set: {accuracy:.2f}")

# Save the trained model
nlp.to_disk("expense_nlp")
print("Model training complete and saved as 'expense_nlp'")


# Function to test the model on individual items
def test_categorization(items):
    results = []
    for item in items:
        doc = nlp(item)
        predicted_category = max(doc.cats, key=doc.cats.get)
        confidence = doc.cats[predicted_category]
        results.append({
            "item": item,
            "predicted_category": predicted_category,
            "confidence": confidence,
            "all_scores": {cat: score for cat, score in doc.cats.items() if score > 0.05}
        })
    return results


# Test with some common items
test_items = ["carrots", "pizza", "laptop", "bus ticket", "aspirin", "t-shirt"]
results = test_categorization(test_items)

# Display results
for result in results:
    print(f"Item: {result['item']}")
    print(f"Predicted category: {result['predicted_category']} (confidence: {result['confidence']:.2f})")
    print("Other potential categories:")
    for cat, score in result['all_scores'].items():
        if cat != result['predicted_category']:
            print(f"  - {cat}: {score:.2f}")
    print()
