name: NestJS CI Pipeline with Docker

on:
  push:
    branches: [CI]
  pull_request:
    branches: [CI]

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      # Debug step to see repository contents
      - name: List directory contents
        run: |
          echo "Repository root:"
          ls -la
          echo "Back-end directory:"
          ls -la back-end || echo "back-end directory not found"

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "18"
          cache: "npm"
          cache-dependency-path: "./back-end/package.json"

      - name: Install dependencies
        working-directory: ./back-end
        run: npm ci --legacy-peer-deps

      - name: Build application
        working-directory: ./back-end
        run: npm run build

      - name: Run tests
        working-directory: ./back-end
        run: npm run test -- --testPathIgnorePatterns=transactions

      # Optional: Add linting if you need it
      - name: Lint code
        working-directory: ./back-end
        run: npm run lint
        if: always() # Run even if tests fail

      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v4
        with:
          context: ./back-end
          push: true
          tags: ${{ secrets.DOCKER_USERNAME }}/nestjs-app:latest
