name: Flutter CI/CD

on:
  push:
    branches:
      - CI  # Trigger on push to CI branch
  pull_request:
    branches:
      - CI  # Trigger on pull request to CI branch

jobs:
  build:
    runs-on: ubuntu-latest  # Use the latest Ubuntu runner for building

    steps:
      - name: Checkout code
        uses: actions/checkout@v2  # This checks out the code from the repo

      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.24.5'  # Use a specific Flutter version for better stability

      - name: Install dependencies
        run: flutter pub get  # Install project dependencies

      - name: Run tests
        run: flutter test  # Run Flutter unit tests

      - name: Build Flutter APK
        run: flutter build apk --release  # Build the release APK for Android

      - name: Upload APK artifact
        uses: actions/upload-artifact@v2  # Downgraded to v2 for stability
        with:
          name: app-release.apk
          path: build/app/outputs/flutter-apk/app-release.apk  # Path to the APK
    
